version: '3.8'

services:
    tpf-backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
        volumes:
            - .:/var/task
        networks:
            - tpf_shared_network

networks:
    tpf_shared_network:
        external: true
