# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: doneuxservices
service: tpf-backend

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-west-2
    environment:
        DB_HOST: ${env:DB_HOST}
        DB_PORT: ${env:DB_PORT}
        DB_NAME: ${env:DB_NAME}
        DB_USER: ${env:DB_USER}
        DB_PASSWORD: ${env:DB_PASSWORD}

functions:
    app:
        handler: dist/index.handler
        events:
            - http:
                  path: /
                  method: any
            - http:
                  path: /{proxy+}
                  method: any

plugins:
    - serverless-offline

custom:
    serverless-offline:
        httpPort: 3000
        host: 0.0.0.0
